tutor_profil:
    path:  /tutor/{id}
    defaults:  { _controller: AppBundle:Tutor:profil}

company_add:
    path:  /company/add
    defaults:  { _controller: AppBundle:Company:add}

company_profil:
    path:  /company/{id}
    defaults:  { _controller: AppBundle:Company:profil}

announce_list:
    path:  /announce
    defaults:  { _controller: AppBundle:Announce:list}

announce_add:
    path:  /announce/add
    defaults:  { _controller: AppBundle:Announce:add}

announce_profil:
    path:  /announce/{id}
    defaults:  { _controller: AppBundle:Announce:profil}

announce_erase:
    path:  /announce/erase/{id}
    defaults:  { _controller: AppBundle:Announce:erase}

anounce_update:
      path:  /announce/update/{id}
      defaults:  { _controller: AppBundle:Announce:update}

anounce_apply:
      path:  /announce/apply/{id}
      defaults:  { _controller: AppBundle:Announce:apply}

