app:
    resource: "@AppBundle/Controller/"
    type:     annotation

etudiant:
    resource: "@AppBundle/Controller/etudiantController.php"
    prefix:   /
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"